[theme]
base="dark"

primaryColor = "darkred"
#backgroundColor = "#F0FF33"
#secondaryBackgroundColor = "#3183D1"
#textColor = "#03080C"
#font = "sans serif"

[server]
headless = true
#port = $PORT
enableCORS = false
